name: SDSD-phyddle
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.8
  - yaml
  - dendropy
  - graphviz
  - h5py
  - keras
  - matplotlib
  - numpy
  - pandas
  - Pillow
  - pypdf
  - scikit-learn
  - scipy
  - pytorch
  - torchview
  - torchvision
  - tqdm
  - seaborn
